on:
  push:
    branches:
      - develop
      - master

name: Unit test and build

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["18", "20", "22", "24"]
    name: Node ${{ matrix.node }} sample
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          cache: "npm"
          node-version: ${{ matrix.node }}
      - run: npm ci
      - run: npm test
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
  build:
    runs-on: ubuntu-latest
    name: Build package
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          cache: "npm"
          node-version-file: ".nvmrc"
      - run: npm ci
      - run: npm run build
